#!/bin/sh

VS=4.4.157

mkdir -p kernel
cd kernel
wget -c https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${VS}.tar.xz
if [ ! -e linux-${VS} ]; then
    tar xf linux-${VS}.tar.xz;
    mv linux-${VS}/* .
fi
make mrproper
make x86_64_defconfig
make kvmconfig
make -j 16
make modules_prepare
popd

